### ISSUE TITLE
Issue-1 : Create a Responsive Header

### ISSUE THREAD

**Issue by aakriti7x7** [aakriti7x7/Tinkerers-Lab-Website#1]
Make a header with links in the order of **Home**, **Inventory**, **Projects**, **Robocon**, and **FAQ**.
The header should be fixed. Add good animations. The best design will be accepted.

**Comment by AyushTripathiIITP** [comment]
@aakriti7x7 i would like to work for this project can u assign me this issue

**Comment by SattyamSamania** [comment]
Hey @aakriti7x7 Can you please assign this issue to me and tell me further what to do next.

**Comment by Tushar98644** [comment]
I would like to work on it...

**Comment by hexronuspi** [comment]
I've made something related to it, where can i post my files?

**Comment by aakriti7x7** [comment]
You all can work on it and post your screenshot/Working video here, and best design can make a pr

**Comment by hexronuspi** [comment]
Hi,
I am attaching the screenshot, and if any changes are required, suggest it. Comments are most welcome!

![Screenshot (13)](https://user-images.githubusercontent.com/115471257/205711771-58ac4e5a-711e-4e8f-951b-969652b9f570.png)

**Comment by prathamiitp** [comment]
> Hi, I am attaching the screenshot, and if any changes are required, suggest it. Comments are most welcome!
> 
> ![Screenshot (13)](https://user-images.githubusercontent.com/115471257/205711771-58ac4e5a-711e-4e8f-951b-969652b9f570.png)

I have added links to [UI.md](https://github.com/aakriti7x7/Tinkerers-Lab-Website/blob/main/Resources/UI.md) for reference, 
try to improve the design.

**Comment by Tushar98644** [comment]
Suggest changes if neccessary.....

https://user-images.githubusercontent.com/107763774/205720680-4e0464c9-246b-4e4a-8353-fa5e1b6e96b5.mp4

**Comment by aakriti7x7** [comment]
> Suggest changes if neccessary.....
> 
>  Untitled.mp4

follow the color scheme given in /resources/UI

**Comment by hexronuspi** [comment]
I've comeup with something, this'll be the landing page(attached) and the information website will have a color transfusion view like in "advanced.team" website. 

https://user-images.githubusercontent.com/115471257/205931335-58b26dc3-c387-440f-9d14-b8e4fe760247.mp4

**Comment by aakriti7x7** [comment]
> I've comeup with something, this'll be the landing page(attached) and the information website will have a color transfusion view like in "advanced.team" website.
> 
>  test.1.mp4

make the bg purple(shade given in resources), reduce the animation time, and show it in the new issue section... issue 3, landing page

**Comment by AyushTripathiIITP** [comment]
![image](https://user-images.githubusercontent.com/101452500/206099093-684de690-5828-4d08-9603-eb707685c267.png)
I have created this please put forword your suggestions

**Comment by AyushTripathiIITP** [comment]
https://user-images.githubusercontent.com/101452500/206117609-1b0a07c2-2814-4d97-9b87-0a8cf2f8ff54.mp4

I made this responsive header suggest your changes

**Comment by AyushTripathiIITP** [comment]
https://user-images.githubusercontent.com/101452500/206117812-6dbc594d-aed2-48e9-83ca-a9171c2a3d0d.mp4

I made this header please suggest your changes @aakriti7x7 @prathamiitp

**Comment by prathamiitp** [comment]
> Suggest changes if neccessary.....
> 
>  Untitled.mp4

Try to follow colour scheme.
Otherwise the look is good.

**Comment by prathamiitp** [comment]
> 2022_12_07_130844.mp4 
> I made this header please suggest your changes @aakriti7x7 @prathamiitp

The header is too wide, rest is fine.
Make header of standard size.

**Comment by prathamiitp** [comment]
To all the individual working on this, remeber to keep your code inline with the existing Nextjs structure.
If you have any doubts feel free to ask.

**Comment by aakriti7x7** [comment]
> 2022_12_07_130844.mp4 
> I made this header please suggest your changes @aakriti7x7 @prathamiitp

It's looking good; make the picture cover the whole space(horizontally),

**Comment by prathamiitp** [comment]
> 2022_12_07_130844.mp4 
> I made this header please suggest your changes @aakriti7x7 @prathamiitp

if you have reduced the height of the header, open a pull request!

**Comment by prathamiitp** [comment]
> I've comeup with something, this'll be the landing page(attached) and the information website will have a color transfusion view like in "advanced.team" website.
> 
>  test.1.mp4

I will open another issue to make a animation for landing page

after the header is added by @AyushTripathiIITP 
put the animation in the landing page below header 

and then make the pull request in the new issue

**Comment by hexronuspi** [comment]
> > I've comeup with something, this'll be the landing page(attached) and the information website will have a color transfusion view like in "advanced.team" website.
> > test.1.mp4
> 
> I will open another issue to make a animation for landing page
> 
> after the header is added by @AyushTripathiIITP put the animation in the landing page below header
> 
> and then make the pull request in the new issue

What i fail to undestand, what's was wrong in this webpage, 
https://user-images.githubusercontent.com/115471257/206775169-fc88108f-e8e6-4c24-9d3e-175cc9a721ec.mp4
i mean there are much more things to add but it's a good skeleton, isn't it?

**Comment by ankushj0801** [comment]
Can I work on this issue? @aakriti7x7

**Comment by aakriti7x7** [comment]
> Can I work on this issue? @aakriti7x7

yeah I'll assign you the issue

**Comment by prathamiitp** [comment]
issue completed by @AyushTripathiIITP
