### ISSUE TITLE
Issue 2 : Tinkerer's Lab new logo design

### ISSUE THREAD

**Issue by aakriti7x7** [aakriti7x7/Tinkerers-Lab-Website#2]
![WhatsApp Image 2022-12-05 at 7 18 49 PM](https://user-images.githubusercontent.com/74852672/205714594-cd1d2dbe-24e6-4f03-87d0-c9ec53b612a0.jpeg)

This was the previous TL logo, 
need a better-looking logo in the color scheme mentioned in Resources/UI

Make the PR in the [/Resources](https://github.com/aakriti7x7/Tinkerers-Lab-Website/tree/main/Resources) folder

**Comment by Tushar98644** [comment]
Would like to work on the issue...

**Comment by aakriti7x7** [comment]
> Would like to work on the issue...

yeah go ahead

**Comment by ghost** [comment]
I would like to contribute

**Comment by aakriti7x7** [comment]
> I would like to contribute

assigned.

**Comment by nik132-eng** [comment]
If this problem isn't resolved, I'd like to get involved.

**Comment by AyushTripathiIITP** [comment]
![image](https://user-images.githubusercontent.com/101452500/206098751-ce9f2dae-f89d-4bae-918a-a66344582070.png)
i have created this responsive header, I invite suggestion

**Comment by prathamiitp** [comment]
This is an open issue, you can work but only the best design will be selected in the last week.

**Comment by nik132-eng** [comment]
![thinker's lab](https://user-images.githubusercontent.com/77881638/206351530-3d2899b8-92a4-470d-91ed-10c068b7470e.png)

Can you give some suggestions on this?
