### ISSUE TITLE
Issue 3 : Create a Complete, Responsive Landing Page

### ISSUE THREAD

**Issue by aakriti7x7** [aakriti7x7/Tinkerers-Lab-Website#5]
Follow the color scheme
Sections needed
1) LOGO (put any random photo for the logo for now) and about TL (take content from the STC (website).
2) make a card for upcoming Sessions (topic, date, time, and venue) and previous session(topic, highlights)
3) Team:
Overall cod
cod
subcod
volunteer
(put random image and names, but keep the designation correct) 
4) We Provide Assistance and Facilites for - Robocon, e yantra, and Students.

reference - [TL IITG](https://students.iitgn.ac.in/tinkerers-lab), [TL IITR](https://tinkeringlab.iitr.ac.in/)

**Comment by nik132-eng** [comment]
can you give more detail what do ? And provide me this issue for codepeak22 so I may begin my adventure.

**Comment by hexronuspi** [comment]
with reference to, 
https://github.com/aakriti7x7/Tinkerers-Lab-Website/issues/1#issuecomment-1340071807
(i just want to add something like, if we scroll just one time the whole animation page gets shifted to the main page , and i am having a trouble doing it.)

https://user-images.githubusercontent.com/115471257/206226325-3ca59ba0-6610-41ff-86ab-17bff69addd1.mp4

**Comment by aakriti7x7** [comment]
> can you give more detail what do ? And provide me this issue for codepeak22 so I may begin my adventure.

Refer to the two website links given in the description; we want something similar, and yes you can take the issue

**Comment by aakriti7x7** [comment]
> with reference to, [#1 (comment)](https://github.com/aakriti7x7/Tinkerers-Lab-Website/issues/1#issuecomment-1340071807) (i just want to add something like, if we scroll just one time the whole animation page gets shifted to the main page , and i am having a trouble doing it.)
> 
>  profile1.mp4

You can work with the design and colors a bit more; refer to the links, specifically the tinkerer's lab website of IIT Gandhinagar

**Comment by Tushar98644** [comment]
i have seen the websites for IITR and IITGn and i think i can design something similar .....would like to take up the issue ...

**Comment by prathamiitp** [comment]
> i have seen the websites for IITR and IITGn and i think i can design something similar .....would like to take up the issue ...

cool
start the work, will assign it to you
